### Hello world! 
### This is @WildDataBeast | Jamar Anthony Almaraz, 6/1/2020

# PROJECT: IN WHAT MAJOR CITY SHOULD I OPEN A NEW COFFEE SHOP?

--------------------------------------

# WEEK 1

# PROBLEM STATEMENT AND BACKGROUND:
Data Cafe is having extreme success in their new location in downtown Chicago. Data Cafe has also concluded that its brand and customer outreach has grown signficantly by simply being in a major city's high traffic area. To keep this growth momentum going, Data Cafe is looking to open a new coffee shop in another major US city. The question is where? 

Data Cafe's CEO has asked WildDataBeast to help with a comprehensive analysis on each major city's center, including a short comnpare and contrast on the market between the top ten major cities including Chicago. 


# DESCRIPTION OF DATA AND PROBLEM SOLVING METHOD:

In order to complete this task, WildDataBeast has decided to:
1. Web scrape a dataframe of major US cities found on Wikipedia
2. Clean and format data
3. Lock in on major cities in the US (the top 10) .

    1. Chicago - Congress Plaza Hotel, Data Cafe
    2. New York - City Hall
    3. Houston - One Shell Plaza
    4. Phoenix - City Hall
    5. Philadelphia - City Hall
    6. San Antonio - City Hall
    7. San Jose - Downtown Historic District
    8. San Diego - Civic Center
    9. Los Angeles - City Hall
    10. Dallas - City Hall


4. Obtain latitude and longitude coordinates for each city and map them
5. Use Foursquare API to pull 100 venues from each city center's radius
6. Format each venue into binary data grouped by city (have or dont have)
7. Normalize the binary venue data into means for comparison
8. Use kmeans from sklearn library to cluster each city using the normalized binary data.
9. Visualize the data by:  
    1. Dataframes per cluster assigned (see similar cities by venue)
    2. Dataframe with top 10 venue category per city (see venue types)
    3. Map the clusters (visualize cluster location)
    4. Create an array display of the top 20 venue category by count (see where coffee shops falls in for each major city)

10. Explore data

# WEEK 2:

# BUSINESS PROBLEM AND AUDIENCE:
The business problem is that business growth is needed if Data Cafe wants to outsurvive in the ever innovating coffee shop industry. It is especially important for a coffee shop to make a name for itself and become known as a household name in order to compete with other well known establishments. 

Therefor, location is king in the coffee shop industry and there is no better locations than bussling areas full of corporate workers and college students in a major US city center. 

This exploratory analysis on market venues of each major US city is vital information for any CEO with a vision to grow, and grow fast. It is even more important to understand what is the compitition in a particular area, if there are any complimentery businesses in an area, or if there is a specific footprint dying for a coffee shop to be opened within a short walk. 


# ABOUT THE DATA USED:
The data used to identify the largest major cities in the US by population came from infoplease.com (see source link below). Here the 2010 Census was used, assuming that these major US cities have sustained their postition, at the very least the top 10 cities other than Chicago. 

The data used to identify venues within each city's center was pulled using the Foursquare API. A limit of 100 venues per city was used. The radius was increased to maximize the limit of venues per city center in order to capture as many nearby venues per city center as allowed. 

Major US Cities by Population Source:
https://www.infoplease.com/us/us-cities/top-50-cities-us-population-and-rank

Venue Information Source:
https://foursquare.com/


# METHODOLOGY:

1. Mapping the Selected Major Cities. 
First order of business after web scraping the required data needed, I used the folium library to map out the location of the top 10 major cities in the US, including Chicago. The mapping center is the center provided by geocoder by simply using X, USA where X is the name of the city. By mapping the coordinates used for each city, I was able to verify that these coordinates are correct and about where each major city's downtown area is located. 

2. Use FourSquare API to Obtain Venues in each Major City 
I then used a Foursquare API to pull exactly 100 venues within a specified radius from each major city's downtown coordinates. I increased the size of the radius of each city's downtown coordinates (kept same size radius per city) until each city hit the limit of 100 venues per city. 

3. Unsupervised Machine Learning: K-Means Clustering 
I used kmeans clusteirng from sklearn library to cluster each city based on venue categories. This meant Data Cafe fell within the Coffee Shop venue category. Since there are 10 cities with 100 venues each, this meant there was 1000 venues to categorize and format into a dataframe that could group each venue by city and display each venue category as a binary value, have or dont have this venue category per city. The purpose of this was not only to normalize the binary data by means, but to use this data for clustering. By clustering each major city with a label, we are able to see what major cities have in common or don't have in common with each other. This exersice would should if there are any oppurtunities that would drive the same success that Data Cafe has had in Chicago in another similar city. With labels obtained, I was then able color code each major city on a map. 


4. Visualize the Data in Various Ways: 
To further explore findings beyond clustering labels, I decided to create a dataframe that displays the top 10 venue categories per city. This would help in comparing what similarities does each city have when it comes to the many other venue categories such as pizza places, parks, restuarants, and many other types of businesses. This would also aid in understanding what the market looks for in each area and understanding if there are any gaps that Data Cafe can exploit. 

To understand how much of each venue category there is per city center, I created an array to display the top 20 venue categories by sum of each venue. This would aid in understanding how much of each venue exist per city. Then understand if there is a coorelation between venue types. I found that there is a mean of 5 coffee shops in proximity to each major city's center (range of 3 to 11, Phoenix with the most), not including San Antonio, which only had 1 coffee shop (and found to be a little crazy, 14 hotels around its city hall).
    


# RESULTS:

By using K-means clustering, 

By using the Venue Count Dataframe created, I found that the top 10 major cities have anywhere between 1 to 11 coffee shops near its city center. This finding resulted in a mean of 5 coffee shops for the top ten major cities, not including San Antonio, which only had one near by coffee shop, despite ranking number 7 by population. San Antonio seems to be an outlier when it comes to coffee shop venues located near its city hall. What also stood out by San Antonio is that Hotels, American Restaurants, Museums, Plazas, and theaters ranked as the top 5 venues near its city hall.


**SAN ANTONIO'S TOP VENUES AND COUNT**
1. Hotel- 14
2. American Restaurant- 6
3. Museum- 4
4. Plaza- 3
5. Theater- 3
...
31. Theater- 1

Coffee shops were also in the top three venue category counts for 6 major US city centers. 

**CITIES WHERE COFFEE SHOPS IS RANKED NUMBER 1 VENUE BY COUNT
1. Phoenix with 11
2. Philadelphia with 6

**CITIES WHERE COFFEE SHOPS IS RANKED NUMBER 2 VENUE BY COUNT
1. Dallas with 6
2. Los Angeles with 5
3. San Jose with 3 

**CITIES WHERE COFFEE SHOPS ARE NOT RANKED IN THE TOP 5 VENUES BY COUNT
1. New York with 3 (ranking at number 6)
2. Chicago with 3 (ranking at number 6)
3. San Diego with 3 (ranking at number 7)
4. San Antonio with 1 (ranking at number 31)


# DISCUSSION AND CONCLUSION:

After further analysis I found that the data does not indicate conclude the total population count of coffee shop venues in a city, but it does show that within a specific radius indicated that there is a certain number of coffee shops. Since there is a limit of 100 venues per city, it may be that the indicated area for each city may be saturated with other venues that coffee shops do not appear as frequently. Examples would be Chicago, there is a heavier density of various venues with the specified area that coffee shops may not even rank high in comparison to other venue categories. What it does indicate is that in location such as San Antonio (with 1 coffee shop in proximity) and Phoenix (with 11 coffee shops) do deserve more investigation into the market. Why is it that there is only 1 coffee shop near the City Hall of San Antonio, but 14 hotels? Why is it that Phoenix's City Hall has 11 coffee shops, 7 art galleries, and 6 pizza places as some of the most frequent venues closest to its City Hall? These may be worthy questions to explore further and understand what is different.   

To diver deeper into San Antonio:

Singling out San Antonio as an outlier in coffee shop frequency within proximity of its city hall, I did further investigation. Assuming that Foursquare data prvided is accurate and up-to-date, I found that the closest coffee shop to City Hall of San Antonio is a half a mile away which is a Starbucks. After finding this information a bit unbelievable, I did a simple google search on "coffee shops near City Hall of San Antonio" and found that there is a 7-Eleven which is more of convenience store, but nonetheless a source for anyone looking for a cup of coffee. Though the coffee from 7-Eleven may not be the quality most coffee enthusiast would seek. Based off this information, Data Cafe should further explore an oppurtunity in San Antonio, and better understand why other US major cities have Coffee Shops in their top 5 venues while San Antonio does not. 

These finding conclude that the CEO of Data Cafe should seek further market analysis in San Antonio for company growth oppurtunities. 

# PRESENTATION / EXPLORATORY VISUALS
SEE BOTTOM OF CODE FOR #PRESENTATION

## First Order: Web Mine Data on Major Cities

#### Import Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
#import sys
#!{sys.executable} -m pip install beautifulsoup4

In [3]:
from bs4 import BeautifulSoup

In [4]:
import urllib.request

#### Target Wikipedia Page

In [5]:
URL = "https://www.infoplease.com/us/us-cities/top-50-cities-us-population-and-rank"

#### Open the URL using URLLIB.REQUEST object

In [6]:
page = urllib.request.urlopen(URL)

#### Parse the HTML from the Wikipedia page into the BeatifulSoup Parse Tree Format

In [7]:
soup = BeautifulSoup(page, "lxml")

In [8]:
# print(soup.prettify())

#### Here is the title of the table

In [9]:
soup.title.string

'Top 50 Cities in the U.S. by Population and Rank'

#### Here I am selecting and sorting through each table

In [10]:
all_tables = soup.find_all('table')
# all_tables

#### This selects the correct table called sgmltable

In [11]:
right_table = soup.find('table',class_='sgmltable')
# right_table

#### This function will then pull each text from each box and place it in a list as the function runs through each column

In [12]:
#Rank
A= []
#City
B= []
#Population Estimate
C= []
#2010 Census
D= []
#2000 Census
E= []
#1990 Census
F= []

#For loop function that for every row in the rightable row <tr>
# it will append each cell into the empty cell. 

for row in right_table.findAll('tr'):
    cells=row.findAll('td')
    if len(cells)==6:
        A.append(cells[0].find(text=True))
        B.append(cells[1].find(text=True))
        C.append(cells[2].find(text=True))
        D.append(cells[3].find(text=True))
        E.append(cells[4].find(text=True))
        F.append(cells[5].find(text=True))

#### Here I am displaying the information pulled from each column

In [13]:
A

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50']

#### Here I am creating column A as dataframe, then adding each column to the dataframe

In [14]:
df=pd.DataFrame(A,columns=['Rank'])
df['City']=B
df['Population_Est']=C
df['2010_Census']=D
df['2000_Census']=E
df['1990_Census']=F
df

,Rank,City,Population_Est,2010_Census,2000_Census,1990_Census
0,1,New York,"8,336,817","8,175,133","8,008,278","7,322,564"
1,2,Los Angeles,"3,979,576","3,792,621","3,694,820","3,485,398"
2,3,Chicago,"2,693,976","2,695,598","2,896,016","2,783,726"
3,4,Houston,"2,320,268","2,100,263","1,953,631","1,630,553"
4,5,Phoenix,"1,680,992","1,445,632","1,321,045","983,403"
5,6,Philadelphia,"1,584,064","1,526,006","1,517,550","1,585,577"
6,7,San Antonio,"1,547,253","1,327,407","1,144,646","935,933"
7,8,San Diego,"1,423,851","1,307,402","1,223,400","1,110,549"
8,9,Dallas,"1,343,573","1,197,816","1,188,580","1,006,877"
9,10,San Jose,"1,021,795","945,942","894,943","782,248"
10,11,Austin,"978,908","790,390","656,562","465,622"
11,12,"Jacksonville,","911,507","821,784","735,617","635,230"
12,13,Fort Worth,"909,585","741,206","534,694","447,619"
13,14,Columbus,"898,553","787,033","711,470","632,910"
14,15,Charlotte,"885,708","731,424","540,828","395,934"
15,16,San Francisco,"881,549","805,235","776,733","723,959"
16,17,Indianapolis,"876,384","820,445","781,870","741,952"
17,18,Seattle,"753,675","608,660","563,374","516,259"
18,19,Denver,"727,211","600,158","554,636","467,610"
19,20,"Washington, DC","705,749","601,723","572,059","606,900"
20,21,Boston,"692,600","617,594","589,141","574,283"
21,22,El Paso,"681,728","649,121","563,662","515,342"
22,23,Nashville-Davidson,"670,820","601,222","545,524","510,784"
23,24,Detroit,"670,031","713,777","951,270","1,027,974"
24,25,Oklahoma City,"655,057","579,999","506,132","444,719"
25,26,Portland,"654,741","583,776","529,121","437,319"
26,27,Las Vegas,"651,319","583,756","478,434","258,295"
27,28,Memphis,"651,073","646,889","650,100","610,337"
28,29,Louisville-Jefferson County,"617,638","597,337","256,231","269,063"
29,30,Baltimore,"593,490","620,961","651,154","736,014"
30,31,Milwaukee,"590,157","594,833","596,974","628,088"
31,32,Albuquerque,"560,513","545,852","448,607","384,736"
32,33,Tucson,"548,073","520,116","486,699","405,390"
33,34,Fresno,"531,576","494,665","427,652","354,202"
34,35,Mesa,"518,012","439,041","396,375","288,091"
35,36,Sacramento,"513,624","466,488","407,018","369,365"
36,37,Atlanta,"506,811","420,003","416,474","394,017"
37,38,Kansas City,"495,327","459,787","441,545","435,146"
38,39,Colorado Springs,"478,221","416,427","360,890","281,140"
39,40,Omaha,"478,192","408,958","390,007","335,795"
40,41,Raleigh,"474,069","403,892","276,093","207,951"
41,42,Miami,"467,963","399,457","362,470","358,548"
42,43,Long Beach,"462,628","462,257","461,522","429,433"
43,44,Virginia Beach,"449,974","437,994","425,257","393,069"
44,45,Oakland,"433,031","390,724","399,484","372,242"
45,46,Minneapolis,"429,606","382,578","382,618","368,383"
46,47,Tulsa,"401,190","391,906","393,049","367,302"
47,48,Tampa,"399,700","335,709","303,447","280,015"
48,49,Arlington,"398,854","365,438","332,969","261,721"
49,50,New Orleans,"390,144","343,829","484,674","495,080"

#### Here the column data types are shown

In [15]:
df.dtypes

Rank              object
City              object
Population_Est    object
2010_Census       object
2000_Census       object
1990_Census       object
dtype: object

#### This will select only the columns needed

In [16]:
df1 = df[["Population_Est", "City", "2010_Census"]]

#### Here df1 is redefined as only the top 10 cities Data Cafe is focusing on

In [17]:
df1 = df1.iloc[0:10]
df1

  Population_Est          City 2010_Census
0      8,336,817      New York   8,175,133
1      3,979,576   Los Angeles   3,792,621
2      2,693,976       Chicago   2,695,598
3      2,320,268       Houston   2,100,263
4      1,680,992       Phoenix   1,445,632
5      1,584,064  Philadelphia   1,526,006
6      1,547,253   San Antonio   1,327,407
7      1,423,851     San Diego   1,307,402
8      1,343,573        Dallas   1,197,816
9      1,021,795      San Jose     945,942

#### Here df1 is being renamed to TopTen

In [18]:
TopTen = df1

In [19]:
TopTen.shape

(10, 3)

## Second Order: Pulling Coordinates Using GeoCoder into the TopTen Dataframe

In [20]:
pip install geopy

Requirement already satisfied: geopy in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (1.22.0)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from geopy) (1.50)
Note: you may need to restart the kernel to use updated packages.

In [21]:
pip install geocoder

Requirement already satisfied: geocoder in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (1.38.1)
Requirement already satisfied: ratelim in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from geocoder) (0.1.6)
Requirement already satisfied: six in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from geocoder) (1.14.0)
Requirement already satisfied: click in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from geocoder) (7.0)
Requirement already satisfied: future in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from geocoder) (0.18.2)
Requirement already satisfied: requests in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from geocoder) (2.22.0)
Requirement already satisfied: decorator in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from ratelim->geocoder) (4.4.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from requests->geocoder) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from requests->geocoder) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\jalma\documents\anaconda3\anaconda3_files\lib\site-packages (from requests->geocoder) (1.25.8)
Note: you may need to restart the kernel to use updated packages.

In [22]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

#!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

Libraries imported.

#### Import RateLimter

In [23]:
from geopy.extra.rate_limiter import RateLimiter

In [24]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="GeoWildDataBeast")
location = geolocator.geocode("Chicago, Illinois")
print(location.address)
print((location.latitude, location.longitude))
print(location.raw)

Chicago, Cook County, Illinois, United States of America
(41.8755616, -87.6244212)
{'place_id': 235244846, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'relation', 'osm_id': 122604, 'boundingbox': ['41.644531', '42.0230396', '-87.940101', '-87.5240812'], 'lat': '41.8755616', 'lon': '-87.6244212', 'display_name': 'Chicago, Cook County, Illinois, United States of America', 'class': 'boundary', 'type': 'administrative', 'importance': 0.9715295727100248, 'icon': 'https://nominatim.openstreetmap.org/images/mapicons/poi_boundary_administrative.p.20.png'}

#### Create a RateLimiter Constructor

In [25]:
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

In [26]:
TopTen['CityLocation'] = TopTen['City'] + ", United States"
TopTen.head(3)

  Population_Est         City 2010_Census                CityLocation
0      8,336,817     New York   8,175,133     New York, United States
1      3,979,576  Los Angeles   3,792,621  Los Angeles, United States
2      2,693,976      Chicago   2,695,598      Chicago, United States

In [27]:
TopTen["GeoLocation"] = TopTen["CityLocation"].apply(geocode)
TopTen.head(3)

,Population_Est,City,2010_Census,CityLocation,GeoLocation
0,"8,336,817",New York,"8,175,133","New York, United States","(New York, United States of America, (40.71272..."
1,"3,979,576",Los Angeles,"3,792,621","Los Angeles, United States","(Los Angeles, Los Angeles County, California, ..."
2,"2,693,976",Chicago,"2,695,598","Chicago, United States","(Chicago, Cook County, Illinois, United States..."

In [28]:
TopTen['Point'] = TopTen['GeoLocation'].apply(lambda loc: tuple(loc.point) if loc else None)
TopTen.head(3)

,Population_Est,City,2010_Census,CityLocation,GeoLocation,Point
0,"8,336,817",New York,"8,175,133","New York, United States","(New York, United States of America, (40.71272...","(40.7127281, -74.0060152, 0.0)"
1,"3,979,576",Los Angeles,"3,792,621","Los Angeles, United States","(Los Angeles, Los Angeles County, California, ...","(34.0536909, -118.2427666, 0.0)"
2,"2,693,976",Chicago,"2,695,598","Chicago, United States","(Chicago, Cook County, Illinois, United States...","(41.8755616, -87.6244212, 0.0)"

In [29]:
TopTen[['Latitude', 'Longitude', 'Altitude']] = pd.DataFrame(TopTen['Point'].tolist(), index=TopTen.index)
TopTen.head(3)

,Population_Est,City,2010_Census,CityLocation,GeoLocation,Point,Latitude,Longitude,Altitude
0,"8,336,817",New York,"8,175,133","New York, United States","(New York, United States of America, (40.71272...","(40.7127281, -74.0060152, 0.0)",40.712728,-74.006015,0.0
1,"3,979,576",Los Angeles,"3,792,621","Los Angeles, United States","(Los Angeles, Los Angeles County, California, ...","(34.0536909, -118.2427666, 0.0)",34.053691,-118.242767,0.0
2,"2,693,976",Chicago,"2,695,598","Chicago, United States","(Chicago, Cook County, Illinois, United States...","(41.8755616, -87.6244212, 0.0)",41.875562,-87.624421,0.0

In [30]:
del TopTen["Altitude"]

In [31]:
address = "Chicago, Illinois, United States"
geolocator = Nominatim(user_agent="GeoWildDataBeast") #create a geolocator class
location = geolocator.geocode(address) #geolocater intance 
latitude = location.latitude #creates an instance for location as latitude
longitude = location.longitude #creates an instance for location as longitude
print(latitude, longitude) #prints the address input and outputs coordinates

41.8755616 -87.6244212

In [32]:
MAP = folium.Map(location=[41.500000, -100], zoom_start=4)

# add markers to map
for lat, lng, City in zip(TopTen['Latitude'], TopTen['Longitude'], TopTen['City']):
    label = City
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius= 7,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.4,
        parse_html=False).add_to(MAP)  
    
MAP

## Third Order: Pull Venue Information for each Coordinate using API

In [33]:
CLIENT_ID = '3LOX1XCTNAEPXKSWU1NEMIZB21FN4YVONAVZSSUFFQS2BR3K' # your Foursquare ID
CLIENT_SECRET = 'JIMJSWLBD5UVHYYVUX34PBRAFB51G22ADXPDBJYNYN2NBDC0' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 3LOX1XCTNAEPXKSWU1NEMIZB21FN4YVONAVZSSUFFQS2BR3K
CLIENT_SECRET:JIMJSWLBD5UVHYYVUX34PBRAFB51G22ADXPDBJYNYN2NBDC0

In [34]:
TopTen.loc[0, 'City']

'New York'

In [35]:
City_latitude = TopTen.loc[0, 'Latitude'] # City latitude value
City_longitude = TopTen.loc[0, 'Longitude'] # City longitude value

TopTen_name = TopTen.loc[0, 'City'] # City name

print('Latitude and longitude values of {} are {}, {}.'.format(TopTen_name, 
                                                               City_latitude, 
                                                               City_longitude))

Latitude and longitude values of New York are 40.7127281, -74.0060152.

In [36]:
LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 1000 # define radius
# create URL
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    City_latitude, 
    City_longitude, 
    radius, 
    LIMIT)
url # display URL

'https://api.foursquare.com/v2/venues/explore?&client_id=3LOX1XCTNAEPXKSWU1NEMIZB21FN4YVONAVZSSUFFQS2BR3K&client_secret=JIMJSWLBD5UVHYYVUX34PBRAFB51G22ADXPDBJYNYN2NBDC0&v=20180604&ll=40.7127281,-74.0060152&radius=1000&limit=100'

In [37]:
results = requests.get(url).json()
# results

#### This function will extract the categories from each row when used, and let you know if there none if none listed

In [38]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#### Here I am pulling all the venues from New York into a package for testing

In [39]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

# nearby_venues

C:\Users\jalma\Documents\Anaconda3\Anaconda3_Files\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  This is separate from the ipykernel package so we can avoid doing imports until

In [40]:
print('{} venues were returned by Foursquare.'.format(nearby_venues.shape[0]))

100 venues were returned by Foursquare.

#### This function will now run through all Major Cities and pull venues in its immediate downtown area

In [41]:
def getNearbyVenues(names, latitudes, longitudes, radius=2000):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['City', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [44]:
TopTen_venues = getNearbyVenues(names=TopTen['City'],
                                   latitudes=TopTen['Latitude'],
                                   longitudes=TopTen['Longitude']
                                  )

New York
Los Angeles
Chicago
Houston
Phoenix
Philadelphia
San Antonio
San Diego
Dallas
San Jose

In [45]:
print(TopTen_venues.shape)
TopTen_venues.head()

(1000, 7)

,City,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,New York,40.712728,-74.006015,The Bar Room at Temple Court,40.711448,-74.006802,Hotel Bar
1,New York,40.712728,-74.006015,"The Beekman, A Thompson Hotel",40.711173,-74.006702,Hotel
2,New York,40.712728,-74.006015,The Class by Taryn Toomey,40.712753,-74.008734,Gym / Fitness Center
3,New York,40.712728,-74.006015,Alba Dry Cleaner & Tailor,40.711434,-74.006272,Laundry Service
4,New York,40.712728,-74.006015,City Hall Park,40.712415,-74.006724,Park

In [46]:
TopTen_venues.groupby('City').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
City,,,,,,
Chicago,100,100,100,100,100,100
Dallas,100,100,100,100,100,100
Houston,100,100,100,100,100,100
Los Angeles,100,100,100,100,100,100
New York,100,100,100,100,100,100
Philadelphia,100,100,100,100,100,100
Phoenix,100,100,100,100,100,100
San Antonio,100,100,100,100,100,100
San Diego,100,100,100,100,100,100
San Jose,100,100,100,100,100,100

In [47]:
print('There are {} uniques categories.'.format(len(TopTen_venues['Venue Category'].unique())))

There are 213 uniques categories.

In [48]:
#one hot encoding
TopTen_onehot = pd.get_dummies(TopTen_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
TopTen_onehot['City'] = TopTen_venues['City'] 

# move neighborhood column to the first column
fixed_columns = [TopTen_onehot.columns[-1]] + list(TopTen_onehot.columns[:-1])
TopTen_onehot = TopTen_onehot[fixed_columns]

TopTen_onehot.head()

,City,American Restaurant,Amphitheater,Antique Shop,Aquarium,Arcade,Art Gallery,Art Museum,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Auditorium,BBQ Joint,Bagel Shop,Bakery,Bar,Baseball Stadium,Basketball Stadium,Beer Bar,Beer Garden,Beer Store,Belgian Restaurant,Bistro,Bookstore,Boutique,Brazilian Restaurant,Breakfast Spot,Brewery,Bridge,Bubble Tea Shop,Building,Burger Joint,Café,Cajun / Creole Restaurant,Candy Store,Caribbean Restaurant,Cheese Shop,Chinese Restaurant,Chocolate Shop,Church,Climbing Gym,Clothing Store,Cocktail Bar,Coffee Shop,Comedy Club,Comfort Food Restaurant,Comic Shop,Concert Hall,Convenience Store,Cooking School,Cosmetics Shop,Cuban Restaurant,Cupcake Shop,Cycle Studio,Dance Studio,Deli / Bodega,Department Store,Dessert Shop,Diner,Dive Bar,Dog Run,Donut Shop,English Restaurant,Ethiopian Restaurant,Event Service,Falafel Restaurant,Farmers Market,Filipino Restaurant,Flea Market,Food Court,Food Truck,Fountain,French Restaurant,Fried Chicken Joint,Frozen Yogurt Shop,Furniture / Home Store,Garden,Garden Center,Gas Station,Gastropub,Gay Bar,General College & University,General Entertainment,German Restaurant,Gift Shop,Gourmet Shop,Greek Restaurant,Grocery Store,Gym,Gym / Fitness Center,Harbor / Marina,Hawaiian Restaurant,Health Food Store,Historic Site,History Museum,Hockey Arena,Hookah Bar,Hostel,Hot Dog Joint,Hotel,Hotel Bar,IT Services,Ice Cream Shop,Indian Restaurant,Indie Movie Theater,Indie Theater,Israeli Restaurant,Italian Restaurant,Japanese Restaurant,Jazz Club,Juice Bar,Korean Restaurant,Latin American Restaurant,Laundry Service,Library,Lingerie Store,Liquor Store,Lounge,Malay Restaurant,Market,Massage Studio,Mediterranean Restaurant,Memorial Site,Men's Store,Mexican Restaurant,Middle Eastern Restaurant,Miscellaneous Shop,Mobile Phone Shop,Molecular Gastronomy Restaurant,Monument / Landmark,Movie Theater,Multiplex,Museum,Music Venue,National Park,Neighborhood,New American Restaurant,Night Market,Non-Profit,Noodle House,Office,Opera House,Optical Shop,Organic Grocery,Other Great Outdoors,Outdoor Sculpture,Paper / Office Supplies Store,Park,Pedestrian Plaza,Performing Arts Venue,Pet Café,Pet Service,Pet Store,Pharmacy,Piano Bar,Pie Shop,Pier,Pilates Studio,Pizza Place,Playground,Plaza,Poke Place,Pool,Portuguese Restaurant,Pub,Public Art,Ramen Restaurant,Residential Building (Apartment / Condo),Resort,Restaurant,Rock Club,Salad Place,Salon / Barbershop,Sandwich Place,Scenic Lookout,School,Science Museum,Sculpture Garden,Seafood Restaurant,Shipping Store,Shopping Mall,Skate Park,Skating Rink,Snack Place,Soccer Stadium,Southern / Soul Food Restaurant,Spa,Speakeasy,Sporting Goods Shop,Sports Bar,Sports Club,Stationery Store,Steakhouse,Supermarket,Sushi Restaurant,Taco Place,Tea Room,Thai Restaurant,Theater,Theme Restaurant,Tour Provider,Toy / Game Store,Trail,Turkish Restaurant,Udon Restaurant,Vegetarian / Vegan Restaurant,Vietnamese Restaurant,Volleyball Court,Waterfront,Whisky Bar,Wine Bar,Wings Joint,Women's Store,Yoga Studio
0,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [49]:
TopTen_onehot.shape

(1000, 214)

In [50]:
TopTen_grouped = TopTen_onehot.groupby('City').mean().reset_index()
TopTen_grouped

,City,American Restaurant,Amphitheater,Antique Shop,Aquarium,Arcade,Art Gallery,Art Museum,Arts & Crafts Store,Asian Restaurant,Athletics & Sports,Auditorium,BBQ Joint,Bagel Shop,Bakery,Bar,Baseball Stadium,Basketball Stadium,Beer Bar,Beer Garden,Beer Store,Belgian Restaurant,Bistro,Bookstore,Boutique,Brazilian Restaurant,Breakfast Spot,Brewery,Bridge,Bubble Tea Shop,Building,Burger Joint,Café,Cajun / Creole Restaurant,Candy Store,Caribbean Restaurant,Cheese Shop,Chinese Restaurant,Chocolate Shop,Church,Climbing Gym,Clothing Store,Cocktail Bar,Coffee Shop,Comedy Club,Comfort Food Restaurant,Comic Shop,Concert Hall,Convenience Store,Cooking School,Cosmetics Shop,Cuban Restaurant,Cupcake Shop,Cycle Studio,Dance Studio,Deli / Bodega,Department Store,Dessert Shop,Diner,Dive Bar,Dog Run,Donut Shop,English Restaurant,Ethiopian Restaurant,Event Service,Falafel Restaurant,Farmers Market,Filipino Restaurant,Flea Market,Food Court,Food Truck,Fountain,French Restaurant,Fried Chicken Joint,Frozen Yogurt Shop,Furniture / Home Store,Garden,Garden Center,Gas Station,Gastropub,Gay Bar,General College & University,General Entertainment,German Restaurant,Gift Shop,Gourmet Shop,Greek Restaurant,Grocery Store,Gym,Gym / Fitness Center,Harbor / Marina,Hawaiian Restaurant,Health Food Store,Historic Site,History Museum,Hockey Arena,Hookah Bar,Hostel,Hot Dog Joint,Hotel,Hotel Bar,IT Services,Ice Cream Shop,Indian Restaurant,Indie Movie Theater,Indie Theater,Israeli Restaurant,Italian Restaurant,Japanese Restaurant,Jazz Club,Juice Bar,Korean Restaurant,Latin American Restaurant,Laundry Service,Library,Lingerie Store,Liquor Store,Lounge,Malay Restaurant,Market,Massage Studio,Mediterranean Restaurant,Memorial Site,Men's Store,Mexican Restaurant,Middle Eastern Restaurant,Miscellaneous Shop,Mobile Phone Shop,Molecular Gastronomy Restaurant,Monument / Landmark,Movie Theater,Multiplex,Museum,Music Venue,National Park,Neighborhood,New American Restaurant,Night Market,Non-Profit,Noodle House,Office,Opera House,Optical Shop,Organic Grocery,Other Great Outdoors,Outdoor Sculpture,Paper / Office Supplies Store,Park,Pedestrian Plaza,Performing Arts Venue,Pet Café,Pet Service,Pet Store,Pharmacy,Piano Bar,Pie Shop,Pier,Pilates Studio,Pizza Place,Playground,Plaza,Poke Place,Pool,Portuguese Restaurant,Pub,Public Art,Ramen Restaurant,Residential Building (Apartment / Condo),Resort,Restaurant,Rock Club,Salad Place,Salon / Barbershop,Sandwich Place,Scenic Lookout,School,Science Museum,Sculpture Garden,Seafood Restaurant,Shipping Store,Shopping Mall,Skate Park,Skating Rink,Snack Place,Soccer Stadium,Southern / Soul Food Restaurant,Spa,Speakeasy,Sporting Goods Shop,Sports Bar,Sports Club,Stationery Store,Steakhouse,Supermarket,Sushi Restaurant,Taco Place,Tea Room,Thai Restaurant,Theater,Theme Restaurant,Tour Provider,Toy / Game Store,Trail,Turkish Restaurant,Udon Restaurant,Vegetarian / Vegan Restaurant,Vietnamese Restaurant,Volleyball Court,Waterfront,Whisky Bar,Wine Bar,Wings Joint,Women's Store,Yoga Studio
0,Chicago,0.01,0.01,0.00,0.03,0.00,0.00,0.01,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.02,0.02,0.02,0.01,0.00,0.00,0.00,0.02,0.00,0.00,0.01,0.01,0.09,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.01,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.01,0.00,0.06,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.06,0.00,0.01,0.01,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.03
1,Dallas,0.04,0.00,0.00,0.01,0.00,0.00,0.02,0.00,0.01,0.00,0.00,0.01,0.00,0.01,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.03,0.00,0.00,0.00,0.01,0.02,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.06,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.02,0.00,0.02,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.11,0.01,0.01,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.02,0.00,0.00,0.02,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.03,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.01,0.00,0.01,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.04,0.00,0.01,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00
2,Houston,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.05,0.03,0.01,0.02,0.01,0.01,0.00,0.02,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.03,0.02,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.02,0.04,0.00,0.00,0.01,0.02,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.09,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.06,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.01,0.01,0.01,0.00,0.00,0.02,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.01,0.00,0.00,0.00
3,Los Angeles,0.02,0.00,0.00,0.00,0.01,0.02,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.02,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.02,0.03,0.00,0.01,0.00,0.00,0.01,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.01,0.04,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.02,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.06,0.00,0.00,0.00,0.00,0.01,0.03,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.01,0.00,0.01,0.00,0.01,0.03,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.04,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.03,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.01,0.00,0.02,0.03,0.01,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,New York,0.00,0.00,0.01,0.00,0.00,0.01,0.01,0.01,0.01,0.01,0.01,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.03,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.02,0.01,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.01,0.01,0.01,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.01,0.00,0.01,0.01,0.01,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.03,0.02,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.10,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.03,0.01,0.03,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.02,0.02,0.03,0.02,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.01,0.00,0.01,0.01
5,Philadelphia,0.03,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.02,0.01,0.07,0.00,0.01,0.00,0.04,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.02,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.02,0.00,0.03,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.07,0.00,0.00,0.01,0.00,0.00,0.00,0.02,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.01,0.00,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.04,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.02,0.00,0.03,0.00,0.00,0.02,0.02,0.03,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.02,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00
6,Phoenix,0.06,0.00,0.00,0.00,0.01,0.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.01,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.04,0.00,0.00,0.01,0.01,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.06,0.00,0.01,0.00,0.00,0.00,0.02,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.01,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00
7,San Antonio,0.05,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.00,0.00,0.01,0.00,0.02,0.01,0.00,0.00,0.00,0.03,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.02,0.01,0.00,0.01,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.02,0.02,0.00,0.00,0.00,0.00,0.14,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.01,0.00,0.01,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.02,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.01,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.03,0.00,0.00,0.00,0.02,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00,0.03,0.01,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8,San Diego,0.05,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.02,0.02,0.00,0.00,0.00,0.02,0.04,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.01,0.03,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.01,0.09,0.01,0.00,0.02,0.00,0.00,0.00,0.00,0.07,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.01,0.00,0.01,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.03,0.00,0.02,0.02,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.00,0.00,0.00
9,San Jose,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.01,0.00,0.00,0.01,0.01,0.03,0.05,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.01,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.04,0.06,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.02,0.00,0.01,0.01,0.01,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.08,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.03,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.00,0.02,0.00,0.00,0.01,0.04,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.03,0.01,0.00,0.00,0.02,0.00,0.00,0.00,0.01,0.00,0.00,0.02,0.02,0.00,0.00,0.00,0.00,0.01,0.00,0.02

In [51]:
TopTen_grouped.shape

(10, 214)

In [52]:
num_top_venues = 5

for hood in TopTen_grouped['City']:
    print("----"+hood+"----")
    temp = TopTen_grouped[TopTen_grouped['City'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Chicago----
         venue  freq
0        Hotel  0.09
1      Theater  0.06
2         Park  0.06
3  Music Venue  0.04
4  Pizza Place  0.04


----Dallas----
                 venue  freq
0                Hotel  0.11
1          Coffee Shop  0.06
2  American Restaurant  0.04
3                 Park  0.04
4           Steakhouse  0.04


----Houston----
          venue  freq
0         Hotel  0.09
1          Park  0.06
2           Bar  0.05
3   Coffee Shop  0.04
4  Burger Joint  0.03


----Los Angeles----
            venue  freq
0  Ice Cream Shop  0.06
1     Music Venue  0.04
2       Bookstore  0.04
3           Plaza  0.04
4     Coffee Shop  0.04


----New York----
           venue  freq
0           Park  0.10
1  Memorial Site  0.03
2         Bakery  0.03
3          Hotel  0.03
4    Pizza Place  0.03


----Philadelphia----
                 venue  freq
0          Coffee Shop  0.07
1                Hotel  0.07
2         Concert Hall  0.04
3                Plaza  0.04
4  American Restaurant  0.03


----Phoenix----
                 venue  freq
0          Coffee Shop  0.13
1  American Restaurant  0.06
2          Pizza Place  0.06
3          Art Gallery  0.06
4          Music Venue  0.04


----San Antonio----
                 venue  freq
0                Hotel  0.14
1  American Restaurant  0.05
2               Museum  0.04
3           Steakhouse  0.04
4          Beer Garden  0.03


----San Diego----
                 venue  freq
0                Hotel  0.09
1   Italian Restaurant  0.07
2   Mexican Restaurant  0.07
3  American Restaurant  0.05
4                 Café  0.04


----San Jose----
                venue  freq
0  Mexican Restaurant  0.08
1         Coffee Shop  0.06
2                 Bar  0.05
3         Art Gallery  0.04
4      Sandwich Place  0.04

In [53]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

# -------------------------------------------------------------------

# PRESENTATION AND EXPLORATORY VISUALS

# -------------------------------------------------------------------

# DATAFRAME SHOWING MOST COMMON VENUE CATEGORIES PER CITY

In [54]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['City']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
TopTen_venues_sorted = pd.DataFrame(columns=columns)
TopTen_venues_sorted['City'] = TopTen_grouped['City']

for ind in np.arange(TopTen_grouped.shape[0]):
    TopTen_venues_sorted.iloc[ind, 1:] = return_most_common_venues(TopTen_grouped.iloc[ind, :], num_top_venues)

TopTen_venues_sorted

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Chicago,Hotel,Theater,Park,Pizza Place,Music Venue,Yoga Studio,Aquarium,Coffee Shop,History Museum,Gym / Fitness Center
1,Dallas,Hotel,Coffee Shop,American Restaurant,Park,Steakhouse,Plaza,Bar,Brewery,Cocktail Bar,History Museum
2,Houston,Hotel,Park,Bar,Coffee Shop,Baseball Stadium,Mexican Restaurant,Burger Joint,Steakhouse,Italian Restaurant,Lounge
3,Los Angeles,Ice Cream Shop,Coffee Shop,Music Venue,Bookstore,Plaza,Ramen Restaurant,Restaurant,Mexican Restaurant,Japanese Restaurant,Brewery
4,New York,Park,Pizza Place,Coffee Shop,Plaza,Hotel,Sandwich Place,Bakery,Memorial Site,Spa,Scenic Lookout
5,Philadelphia,Coffee Shop,Hotel,Plaza,Concert Hall,Sandwich Place,New American Restaurant,Seafood Restaurant,American Restaurant,Grocery Store,Bakery
6,Phoenix,Coffee Shop,American Restaurant,Art Gallery,Pizza Place,Mexican Restaurant,Music Venue,Hotel,Bar,Southern / Soul Food Restaurant,Cocktail Bar
7,San Antonio,Hotel,American Restaurant,Museum,Steakhouse,Ice Cream Shop,Mexican Restaurant,Restaurant,Plaza,Theater,Beer Garden
8,San Diego,Hotel,Italian Restaurant,Mexican Restaurant,American Restaurant,Café,Bar,Park,Steakhouse,Coffee Shop,Dessert Shop
9,San Jose,Mexican Restaurant,Coffee Shop,Bar,Sandwich Place,Bubble Tea Shop,Cocktail Bar,Art Gallery,Grocery Store,Plaza,Bakery

In [55]:
# set number of clusters
kclusters = 5

TopTen_grouped_clustering = TopTen_grouped.drop('City', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(TopTen_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([4, 0, 0, 3, 4, 0, 1, 0, 0, 2])

In [56]:
# add clustering labels
TopTen_venues_sorted.insert(0, 'Cluster Label', kmeans.labels_)

TopTen_merged = TopTen

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
TopTen_merged = TopTen_merged.join(TopTen_venues_sorted.set_index('City'), on='City')

TopTen_merged # check the last columns!

,Population_Est,City,2010_Census,CityLocation,GeoLocation,Point,Latitude,Longitude,Cluster Label,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,"8,336,817",New York,"8,175,133","New York, United States","(New York, United States of America, (40.71272...","(40.7127281, -74.0060152, 0.0)",40.712728,-74.006015,4,Park,Pizza Place,Coffee Shop,Plaza,Hotel,Sandwich Place,Bakery,Memorial Site,Spa,Scenic Lookout
1,"3,979,576",Los Angeles,"3,792,621","Los Angeles, United States","(Los Angeles, Los Angeles County, California, ...","(34.0536909, -118.2427666, 0.0)",34.053691,-118.242767,3,Ice Cream Shop,Coffee Shop,Music Venue,Bookstore,Plaza,Ramen Restaurant,Restaurant,Mexican Restaurant,Japanese Restaurant,Brewery
2,"2,693,976",Chicago,"2,695,598","Chicago, United States","(Chicago, Cook County, Illinois, United States...","(41.8755616, -87.6244212, 0.0)",41.875562,-87.624421,4,Hotel,Theater,Park,Pizza Place,Music Venue,Yoga Studio,Aquarium,Coffee Shop,History Museum,Gym / Fitness Center
3,"2,320,268",Houston,"2,100,263","Houston, United States","(Houston, Harris County, Texas, United States ...","(29.7589382, -95.3676974, 0.0)",29.758938,-95.367697,0,Hotel,Park,Bar,Coffee Shop,Baseball Stadium,Mexican Restaurant,Burger Joint,Steakhouse,Italian Restaurant,Lounge
4,"1,680,992",Phoenix,"1,445,632","Phoenix, United States","(Phoenix, Maricopa County, Arizona, United Sta...","(33.4484367, -112.0741417, 0.0)",33.448437,-112.074142,1,Coffee Shop,American Restaurant,Art Gallery,Pizza Place,Mexican Restaurant,Music Venue,Hotel,Bar,Southern / Soul Food Restaurant,Cocktail Bar
5,"1,584,064",Philadelphia,"1,526,006","Philadelphia, United States","(Philadelphia, Philadelphia County, Pennsylvan...","(39.9527237, -75.1635262, 0.0)",39.952724,-75.163526,0,Coffee Shop,Hotel,Plaza,Concert Hall,Sandwich Place,New American Restaurant,Seafood Restaurant,American Restaurant,Grocery Store,Bakery
6,"1,547,253",San Antonio,"1,327,407","San Antonio, United States","(San Antonio, Bexar County, Texas, United Stat...","(29.4246002, -98.4951405, 0.0)",29.424600,-98.495141,0,Hotel,American Restaurant,Museum,Steakhouse,Ice Cream Shop,Mexican Restaurant,Restaurant,Plaza,Theater,Beer Garden
7,"1,423,851",San Diego,"1,307,402","San Diego, United States","(San Diego, San Diego County, California, Unit...","(32.7174209, -117.1627714, 0.0)",32.717421,-117.162771,0,Hotel,Italian Restaurant,Mexican Restaurant,American Restaurant,Café,Bar,Park,Steakhouse,Coffee Shop,Dessert Shop
8,"1,343,573",Dallas,"1,197,816","Dallas, United States","(Dallas, Dallas County, Texas, United States o...","(32.7762719, -96.7968559, 0.0)",32.776272,-96.796856,0,Hotel,Coffee Shop,American Restaurant,Park,Steakhouse,Plaza,Bar,Brewery,Cocktail Bar,History Museum
9,"1,021,795",San Jose,"945,942","San Jose, United States","(San Jose, Santa Clara County, California, Uni...","(37.3361905, -121.8905833, 0.0)",37.336191,-121.890583,2,Mexican Restaurant,Coffee Shop,Bar,Sandwich Place,Bubble Tea Shop,Cocktail Bar,Art Gallery,Grocery Store,Plaza,Bakery

In [57]:
TopTen_merged = TopTen_merged[TopTen_merged['Cluster Label'].notnull()]

In [58]:
TopTen_merged.dtypes

Population_Est             object
City                       object
2010_Census                object
CityLocation               object
GeoLocation                object
Point                      object
Latitude                  float64
Longitude                 float64
Cluster Label               int32
1st Most Common Venue      object
2nd Most Common Venue      object
3rd Most Common Venue      object
4th Most Common Venue      object
5th Most Common Venue      object
6th Most Common Venue      object
7th Most Common Venue      object
8th Most Common Venue      object
9th Most Common Venue      object
10th Most Common Venue     object
dtype: object

In [59]:
TopTen_merged['Cluster Label'] = TopTen_merged['Cluster Label'].apply(np.int32)

# CLUSTERS MAPPED FOR VISUAL PRESENTATION

In [60]:
# create map
map_clusters = folium.Map(location=[40, -100], zoom_start=4)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(TopTen_merged['Latitude'], TopTen_merged['Longitude'], TopTen_merged['City'], TopTen_merged['Cluster Label']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=8,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=1).add_to(map_clusters)
       
map_clusters

# CLUSTER 0

In [61]:
TopTen_merged.loc[TopTen_merged['Cluster Label'] == 0, TopTen_merged.columns[[1] + list(range(3, TopTen_merged.shape[1]))]]

,City,CityLocation,GeoLocation,Point,Latitude,Longitude,Cluster Label,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
3,Houston,"Houston, United States","(Houston, Harris County, Texas, United States ...","(29.7589382, -95.3676974, 0.0)",29.758938,-95.367697,0,Hotel,Park,Bar,Coffee Shop,Baseball Stadium,Mexican Restaurant,Burger Joint,Steakhouse,Italian Restaurant,Lounge
5,Philadelphia,"Philadelphia, United States","(Philadelphia, Philadelphia County, Pennsylvan...","(39.9527237, -75.1635262, 0.0)",39.952724,-75.163526,0,Coffee Shop,Hotel,Plaza,Concert Hall,Sandwich Place,New American Restaurant,Seafood Restaurant,American Restaurant,Grocery Store,Bakery
6,San Antonio,"San Antonio, United States","(San Antonio, Bexar County, Texas, United Stat...","(29.4246002, -98.4951405, 0.0)",29.424600,-98.495141,0,Hotel,American Restaurant,Museum,Steakhouse,Ice Cream Shop,Mexican Restaurant,Restaurant,Plaza,Theater,Beer Garden
7,San Diego,"San Diego, United States","(San Diego, San Diego County, California, Unit...","(32.7174209, -117.1627714, 0.0)",32.717421,-117.162771,0,Hotel,Italian Restaurant,Mexican Restaurant,American Restaurant,Café,Bar,Park,Steakhouse,Coffee Shop,Dessert Shop
8,Dallas,"Dallas, United States","(Dallas, Dallas County, Texas, United States o...","(32.7762719, -96.7968559, 0.0)",32.776272,-96.796856,0,Hotel,Coffee Shop,American Restaurant,Park,Steakhouse,Plaza,Bar,Brewery,Cocktail Bar,History Museum

# CLUSTER 1

In [62]:
TopTen_merged.loc[TopTen_merged['Cluster Label'] == 1, TopTen_merged.columns[[1] + list(range(3, TopTen_merged.shape[1]))]]

,City,CityLocation,GeoLocation,Point,Latitude,Longitude,Cluster Label,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
4,Phoenix,"Phoenix, United States","(Phoenix, Maricopa County, Arizona, United Sta...","(33.4484367, -112.0741417, 0.0)",33.448437,-112.074142,1,Coffee Shop,American Restaurant,Art Gallery,Pizza Place,Mexican Restaurant,Music Venue,Hotel,Bar,Southern / Soul Food Restaurant,Cocktail Bar

# CLUSTER 2

In [63]:
TopTen_merged.loc[TopTen_merged['Cluster Label'] == 2, TopTen_merged.columns[[1] + list(range(3, TopTen_merged.shape[1]))]]

,City,CityLocation,GeoLocation,Point,Latitude,Longitude,Cluster Label,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
9,San Jose,"San Jose, United States","(San Jose, Santa Clara County, California, Uni...","(37.3361905, -121.8905833, 0.0)",37.336191,-121.890583,2,Mexican Restaurant,Coffee Shop,Bar,Sandwich Place,Bubble Tea Shop,Cocktail Bar,Art Gallery,Grocery Store,Plaza,Bakery

# CLUSTER 3

In [64]:
TopTen_merged.loc[TopTen_merged['Cluster Label'] == 3, TopTen_merged.columns[[1] + list(range(3, TopTen_merged.shape[1]))]]

,City,CityLocation,GeoLocation,Point,Latitude,Longitude,Cluster Label,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
1,Los Angeles,"Los Angeles, United States","(Los Angeles, Los Angeles County, California, ...","(34.0536909, -118.2427666, 0.0)",34.053691,-118.242767,3,Ice Cream Shop,Coffee Shop,Music Venue,Bookstore,Plaza,Ramen Restaurant,Restaurant,Mexican Restaurant,Japanese Restaurant,Brewery

# CLUSTER 4

In [65]:
TopTen_merged.loc[TopTen_merged['Cluster Label'] == 4, TopTen_merged.columns[[1] + list(range(3, TopTen_merged.shape[1]))]]

,City,CityLocation,GeoLocation,Point,Latitude,Longitude,Cluster Label,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,New York,"New York, United States","(New York, United States of America, (40.71272...","(40.7127281, -74.0060152, 0.0)",40.712728,-74.006015,4,Park,Pizza Place,Coffee Shop,Plaza,Hotel,Sandwich Place,Bakery,Memorial Site,Spa,Scenic Lookout
2,Chicago,"Chicago, United States","(Chicago, Cook County, Illinois, United States...","(41.8755616, -87.6244212, 0.0)",41.875562,-87.624421,4,Hotel,Theater,Park,Pizza Place,Music Venue,Yoga Studio,Aquarium,Coffee Shop,History Museum,Gym / Fitness Center

In [66]:
TopTen_count = TopTen_onehot.groupby('City').sum().reset_index()
#TopTen_count

# Top 50 Venues in Each City Ranked by Frequency

In [67]:
num_top_venues = 50

for hood in TopTen_count['City']:
    print("----"+hood+"----")
    temp = TopTen_count[TopTen_count['City'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Chicago----
                            venue  freq
0                           Hotel   9.0
1                         Theater   6.0
2                            Park   6.0
3                     Music Venue   4.0
4                     Pizza Place   4.0
5                     Yoga Studio   3.0
6                     Coffee Shop   3.0
7                        Aquarium   3.0
8            Gym / Fitness Center   2.0
9                  Breakfast Spot   2.0
10            Arts & Crafts Store   2.0
11                 History Museum   2.0
12                       Fountain   2.0
13                  Grocery Store   2.0
14                            Gym   2.0
15                Harbor / Marina   1.0
16                  Event Service   1.0
17      Middle Eastern Restaurant   1.0
18                   Liquor Store   1.0
19                      Juice Bar   1.0
20                      Gift Shop   1.0
21                      Jazz Club   1.0
22                         Garden   1.0
23            Japanese Restaurant   1.0
24                   Amphitheater   1.0
25            Indie Movie Theater   1.0
26                  Hot Dog Joint   1.0
27                         Hostel   1.0
28                      Multiplex   1.0
29                      Gastropub   1.0
30                   Optical Shop   1.0
31                         Museum   1.0
32                     Skate Park   1.0
33                     Waterfront   1.0
34  Vegetarian / Vegan Restaurant   1.0
35                          Trail   1.0
36               Toy / Game Store   1.0
37                  Tour Provider   1.0
38                     Steakhouse   1.0
39                     Sports Bar   1.0
40            Sporting Goods Shop   1.0
41                   Skating Rink   1.0
42               Sculpture Garden   1.0
43                    Opera House   1.0
44                 Sandwich Place   1.0
45             Salon / Barbershop   1.0
46                    Salad Place   1.0
47                            Pub   1.0
48          Portuguese Restaurant   1.0
49                    Pet Service   1.0


----Dallas----
                       venue  freq
0                      Hotel  11.0
1                Coffee Shop   6.0
2        American Restaurant   4.0
3                       Park   4.0
4                 Steakhouse   4.0
5                        Bar   3.0
6                    Brewery   3.0
7             History Museum   3.0
8                      Plaza   3.0
9               Cocktail Bar   3.0
10         French Restaurant   2.0
11                Food Truck   2.0
12                      Café   2.0
13            Farmers Market   2.0
14                  Dive Bar   2.0
15               Music Venue   2.0
16   New American Restaurant   2.0
17                       Gym   2.0
18             Movie Theater   2.0
19               Pizza Place   2.0
20                Art Museum   2.0
21        Seafood Restaurant   2.0
22                      Pool   1.0
23          Department Store   1.0
24                  Wine Bar   1.0
25                   Theater   1.0
26                     Diner   1.0
27                Taco Place   1.0
28          Sushi Restaurant   1.0
29                Sports Bar   1.0
30             Garden Center   1.0
31               Gas Station   1.0
32            Science Museum   1.0
33            Scenic Lookout   1.0
34            Sandwich Place   1.0
35                 Hotel Bar   1.0
36               IT Services   1.0
37         Indian Restaurant   1.0
38               Salad Place   1.0
39  Mediterranean Restaurant   1.0
40        Mexican Restaurant   1.0
41         Mobile Phone Shop   1.0
42              Concert Hall   1.0
43                 Rock Club   1.0
44             Deli / Bodega   1.0
45        Italian Restaurant   1.0
46                    Bistro   1.0
47                  Aquarium   1.0
48                 BBQ Joint   1.0
49              Burger Joint   1.0


----Houston----
                              venue  freq
0                             Hotel   9.0
1                              Park   6.0
2                               Bar   5.0
3                       Coffee Shop   4.0
4                      Burger Joint   3.0
5                        Steakhouse   3.0
6                Mexican Restaurant   3.0
7                  Baseball Stadium   3.0
8                      Concert Hall   2.0
9                              Café   2.0
10        Cajun / Creole Restaurant   2.0
11                     Cocktail Bar   2.0
12              American Restaurant   2.0
13                       Food Court   2.0
14                           Bistro   2.0
15                           Lounge   2.0
16                      Pizza Place   2.0
17                          Theater   2.0
18                            Trail   2.0
19            Vietnamese Restaurant   2.0
20                          Brewery   2.0
21               Italian Restaurant   2.0
22                         Beer Bar   2.0
23                        BBQ Joint   2.0
24                    Deli / Bodega   1.0
25                         Pharmacy   1.0
26                   Cosmetics Shop   1.0
27                      Supermarket   1.0
28              Japanese Restaurant   1.0
29                     Dance Studio   1.0
30                              Gym   1.0
31                         Dive Bar   1.0
32            Performing Arts Venue   1.0
33  Southern / Soul Food Restaurant   1.0
34                   Soccer Stadium   1.0
35                    Shopping Mall   1.0
36                       Taco Place   1.0
37                       Food Truck   1.0
38               Seafood Restaurant   1.0
39                 Sculpture Garden   1.0
40              Fried Chicken Joint   1.0
41                   Sandwich Place   1.0
42                        Gastropub   1.0
43            Portuguese Restaurant   1.0
44                 Greek Restaurant   1.0
45                 Sushi Restaurant   1.0
46                       Public Art   1.0
47                         Wine Bar   1.0
48                   Clothing Store   1.0
49                       Comic Shop   1.0


----Los Angeles----
                       venue  freq
0             Ice Cream Shop   6.0
1                Music Venue   4.0
2                  Bookstore   4.0
3                      Plaza   4.0
4                Coffee Shop   4.0
5                 Restaurant   3.0
6         Mexican Restaurant   3.0
7                    Theater   3.0
8        Japanese Restaurant   3.0
9           Sushi Restaurant   3.0
10                   Brewery   3.0
11          Ramen Restaurant   3.0
12                       Bar   2.0
13            Breakfast Spot   2.0
14       American Restaurant   2.0
15                    Bakery   2.0
16                 Gastropub   2.0
17       Filipino Restaurant   2.0
18               Art Gallery   2.0
19               Supermarket   2.0
20                 Speakeasy   2.0
21                   Gay Bar   1.0
22         French Restaurant   1.0
23                   Library   1.0
24                Donut Shop   1.0
25                     Hotel   1.0
26                    Market   1.0
27       Fried Chicken Joint   1.0
28             Historic Site   1.0
29             Grocery Store   1.0
30         German Restaurant   1.0
31              Liquor Store   1.0
32                      Park   1.0
33  Mediterranean Restaurant   1.0
34               Men's Store   1.0
35        Miscellaneous Shop   1.0
36             Deli / Bodega   1.0
37          Pedestrian Plaza   1.0
38     Performing Arts Venue   1.0
39                  Pie Shop   1.0
40               Pizza Place   1.0
41            Sandwich Place   1.0
42                    School   1.0
43        Seafood Restaurant   1.0
44             Shopping Mall   1.0
45          Stationery Store   1.0
46                Taco Place   1.0
47           Udon Restaurant   1.0
48                     Diner   1.0
49        Italian Restaurant   1.0


----New York----
                              venue  freq
0                              Park  10.0
1                     Memorial Site   3.0
2                            Bakery   3.0
3                             Hotel   3.0
4                       Pizza Place   3.0
5                             Plaza   3.0
6                       Coffee Shop   3.0
7                    Sandwich Place   3.0
8                       Men's Store   2.0
9              Gym / Fitness Center   2.0
10         Mediterranean Restaurant   2.0
11               Salon / Barbershop   2.0
12                     Cycle Studio   2.0
13                   Scenic Lookout   2.0
14                              Spa   2.0
15                      Salad Place   2.0
16                 Greek Restaurant   1.0
17                     Gourmet Shop   1.0
18                              Gym   1.0
19            General Entertainment   1.0
20           Furniture / Home Store   1.0
21                French Restaurant   1.0
22                    Grocery Store   1.0
23               Falafel Restaurant   1.0
24                        Hotel Bar   1.0
25                   Ice Cream Shop   1.0
26                Indian Restaurant   1.0
27              Indie Movie Theater   1.0
28                    Indie Theater   1.0
29                  Laundry Service   1.0
30                            Diner   1.0
31                       Food Court   1.0
32               Italian Restaurant   1.0
33  Molecular Gastronomy Restaurant   1.0
34              Monument / Landmark   1.0
35                    Women's Store   1.0
36                         Wine Bar   1.0
37                 Volleyball Court   1.0
38    Vegetarian / Vegan Restaurant   1.0
39                  Thai Restaurant   1.0
40                       Taco Place   1.0
41                 Sushi Restaurant   1.0
42                    Shopping Mall   1.0
43               Seafood Restaurant   1.0
44                       Restaurant   1.0
45                       Poke Place   1.0
46                       Playground   1.0
47                   Pilates Studio   1.0
48    Paper / Office Supplies Store   1.0
49                     Noodle House   1.0


----Philadelphia----
                              venue  freq
0                       Coffee Shop   7.0
1                             Hotel   7.0
2                      Concert Hall   4.0
3                             Plaza   4.0
4               American Restaurant   3.0
5                Seafood Restaurant   3.0
6                     Grocery Store   3.0
7                    Sandwich Place   3.0
8                            Bakery   3.0
9           New American Restaurant   3.0
10               Mexican Restaurant   2.0
11                       Art Museum   2.0
12                       Donut Shop   2.0
13                   Clothing Store   2.0
14                     Gourmet Shop   2.0
15               Israeli Restaurant   2.0
16                   Breakfast Spot   2.0
17                             Park   2.0
18                      Pizza Place   2.0
19                     Dessert Shop   2.0
20                   Science Museum   2.0
21                      Salad Place   2.0
22                 Sculpture Garden   2.0
23                       Steakhouse   2.0
24                              Bar   2.0
25                       Taco Place   1.0
26                         Wine Bar   1.0
27               English Restaurant   1.0
28                French Restaurant   1.0
29                        Gastropub   1.0
30    Vegetarian / Vegan Restaurant   1.0
31                        Gift Shop   1.0
32                      Sports Club   1.0
33                         Tea Room   1.0
34                              Gym   1.0
35                 Ramen Restaurant   1.0
36                   Ice Cream Shop   1.0
37                       Restaurant   1.0
38              Japanese Restaurant   1.0
39                 Malay Restaurant   1.0
40                           Market   1.0
41         Mediterranean Restaurant   1.0
42  Southern / Soul Food Restaurant   1.0
43                    Movie Theater   1.0
44                           Museum   1.0
45                    National Park   1.0
46                     Cupcake Shop   1.0
47                  Organic Grocery   1.0
48                      Snack Place   1.0
49               Italian Restaurant   1.0


----Phoenix----
                                       venue  freq
0                                Coffee Shop  13.0
1                        American Restaurant   6.0
2                                Pizza Place   6.0
3                                Art Gallery   6.0
4                                Music Venue   4.0
5                                      Hotel   4.0
6                         Mexican Restaurant   4.0
7            Southern / Soul Food Restaurant   3.0
8                                        Bar   3.0
9                               Cocktail Bar   3.0
10                                  Boutique   2.0
11                                      Park   2.0
12                             Grocery Store   2.0
13                                       Pub   2.0
14                                   Theater   2.0
15                                Food Truck   1.0
16                                     Plaza   1.0
17                             Garden Center   1.0
18                                    Office   1.0
19                               Opera House   1.0
20                             Shopping Mall   1.0
21                            History Museum   1.0
22                            Science Museum   1.0
23                             Historic Site   1.0
24                            Sandwich Place   1.0
25                        Salon / Barbershop   1.0
26                              Dessert Shop   1.0
27                                     Diner   1.0
28                                   Dog Run   1.0
29                                    Garden   1.0
30                            Ice Cream Shop   1.0
31                                    Arcade   1.0
32                      Gym / Fitness Center   1.0
33  Residential Building (Apartment / Condo)   1.0
34                       Fried Chicken Joint   1.0
35                     Performing Arts Venue   1.0
36                                 Rock Club   1.0
37                                  Wine Bar   1.0
38                        Basketball Stadium   1.0
39                                   Brewery   1.0
40                          Baseball Stadium   1.0
41                                 Jazz Club   1.0
42                            Breakfast Spot   1.0
43                                    Lounge   1.0
44                                    Museum   1.0
45                 Cajun / Creole Restaurant   1.0
46                                Taco Place   1.0
47                   New American Restaurant   1.0
48                                    Market   1.0
49                      Caribbean Restaurant   1.0


----San Antonio----
                              venue  freq
0                             Hotel  14.0
1               American Restaurant   5.0
2                            Museum   4.0
3                        Steakhouse   4.0
4                       Beer Garden   3.0
5                    Ice Cream Shop   3.0
6                Mexican Restaurant   3.0
7                             Plaza   3.0
8                        Restaurant   3.0
9                           Theater   3.0
10                             Park   2.0
11          New American Restaurant   2.0
12                     Burger Joint   2.0
13                           Lounge   2.0
14                   Sandwich Place   2.0
15                   History Museum   2.0
16                    Historic Site   2.0
17                     Dessert Shop   2.0
18                     Concert Hall   2.0
19                     Cocktail Bar   2.0
20               Italian Restaurant   2.0
21                           Bakery   2.0
22              Arts & Crafts Store   1.0
23                              Bar   1.0
24                      Flea Market   1.0
25            Performing Arts Venue   1.0
26                   Scenic Lookout   1.0
27                         Fountain   1.0
28  Southern / Soul Food Restaurant   1.0
29               Seafood Restaurant   1.0
30          Comfort Food Restaurant   1.0
31                       Non-Profit   1.0
32                      Coffee Shop   1.0
33                         Dive Bar   1.0
34                 Theme Restaurant   1.0
35                 Asian Restaurant   1.0
36                           Church   1.0
37             Gym / Fitness Center   1.0
38                            Trail   1.0
39                        BBQ Joint   1.0
40                       Art Museum   1.0
41    Vegetarian / Vegan Restaurant   1.0
42                           Resort   1.0
43                    Grocery Store   1.0
44               Belgian Restaurant   1.0
45         Mediterranean Restaurant   1.0
46                        Gastropub   1.0
47                      Men's Store   1.0
48                          Brewery   1.0
49                        Piano Bar   1.0


----San Diego----
                            venue  freq
0                           Hotel   9.0
1              Italian Restaurant   7.0
2              Mexican Restaurant   7.0
3             American Restaurant   5.0
4                            Café   4.0
5                             Bar   3.0
6                     Coffee Shop   3.0
7                      Steakhouse   3.0
8                            Park   3.0
9                      Taco Place   2.0
10                         Museum   2.0
11        New American Restaurant   2.0
12             Seafood Restaurant   2.0
13                   Dessert Shop   2.0
14                      Juice Bar   2.0
15                        Brewery   2.0
16                   Burger Joint   2.0
17                 Breakfast Spot   2.0
18               Sushi Restaurant   2.0
19                 Ice Cream Shop   2.0
20                            Gym   2.0
21              Convenience Store   1.0
22                      Speakeasy   1.0
23                   Cocktail Bar   1.0
24                  Hot Dog Joint   1.0
25                 Cosmetics Shop   1.0
26                      Hotel Bar   1.0
27                     Hookah Bar   1.0
28                     Donut Shop   1.0
29                 Sandwich Place   1.0
30             Salon / Barbershop   1.0
31              Health Food Store   1.0
32             Falafel Restaurant   1.0
33                 Farmers Market   1.0
34               Pedestrian Plaza   1.0
35               Ramen Restaurant   1.0
36                            Pub   1.0
37                           Pier   1.0
38                    Pizza Place   1.0
39                     Beer Store   1.0
40                 Chocolate Shop   1.0
41                   Neighborhood   1.0
42                    Cheese Shop   1.0
43  Vegetarian / Vegan Restaurant   1.0
44                     Whisky Bar   1.0
45             Turkish Restaurant   1.0
46                    Music Venue   1.0
47                       Wine Bar   1.0
48           Brazilian Restaurant   1.0
49                        Theater   1.0


----San Jose----
                            venue  freq
0              Mexican Restaurant   8.0
1                     Coffee Shop   6.0
2                             Bar   5.0
3                     Art Gallery   4.0
4                  Sandwich Place   4.0
5                    Cocktail Bar   4.0
6                 Bubble Tea Shop   4.0
7                   Grocery Store   3.0
8                           Plaza   3.0
9                          Bakery   3.0
10               Sushi Restaurant   3.0
11                        Theater   2.0
12            Japanese Restaurant   2.0
13                          Hotel   2.0
14              German Restaurant   2.0
15                            Pub   2.0
16                    Yoga Studio   2.0
17                     Restaurant   2.0
18          Vietnamese Restaurant   2.0
19  Vegetarian / Vegan Restaurant   2.0
20            Hawaiian Restaurant   1.0
21             Salon / Barbershop   1.0
22           Ethiopian Restaurant   1.0